services:
  postgres:
    image: postgres:15
    container_name: payment_db
    environment:
      POSTGRES_DB: ${DB_NAME:-payment_db}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin_pass}
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: payment_cache
    ports:
      - "6379:6379"

  # Opcional: OpenTelemetry Collector (para centralizar os traces)
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317" # OTLP gRPC
